# "This" bluetooth device as audio source/sink
# 1) apt install pipewire pipewire-audio-client-libraries libspa-0.2-bluetooth bluez
# 2) create this file
# systemctl --user restart pipewire pipewire-pulse wireplumber
[bluez-monitor]
bluez5.enable = true
bluez5.enable-msbc = true
bluez5.enable-sbc-xq = true
bluez5.codecs = [sbc sbc_xq]
bluez5.profile = [ "a2dp-sink" ]
